[features]
seeds = false
skip-lint = false
[programs.localnet]
program = "F1ipperKF9EfD821ZbbYjS319LXYiBmjhzkkf5a26rC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/foskaay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
